travis:
  secure:
    BINSTAR_TOKEN: R33kuQmZOxYa6IsHtNlvRVmQ0+HNrXC0brnvKRqSrpILLTihMDKqijrgG3q6GiN0f8Ru42Hmnmx52hYABw2HhJb102r5gOSGY6xEb4hyD58mTLH3J5DRxWCg/XEllR73eCDkxTKblYWFlkHk78fuxSASCqGkjcV0stCToN5Nm47qnT82JEBJexRnKhJRAvUJu0quGc/3K4dWVcVbilXZVNTUvFe1wu2cQYUvmpSySuo2gYIwIPJ3KUBmQV8YJvn3UR3Q9OM8C60MGCJxC4yQ2KOXTz68+X/2T/sYOsJMeZNTg3+8dOvaPOuUvMRagoApD8VBGNMEpzjRY52j9dUvYm551dJTommYFhXXBmXw9Tjvtjs/2hbvitScJ6q9McMimfnSHHcHuoFGcBBCeN+jeVa/fjxc7gopyBkqwxPwbqdsntro6Opkj1fDYcaQ9mQq5Fpb5HLYrbhGVvubdS1DnkeDN8zkBnD8agZ6SScPMgaRFsCajktrMW1Hzy647WhrG68/mda5Ol/WG9tyDVI2BW9HMMuo4+Fc18cR8SL3Fkv4xba1lL2o11NWvH6hfrS6xddohTYrDImqOvqFUMMWwJF5HNnwDFsb938s3W/Fxv1QAx309eDiPOEjYMJUbf1cGJCnYNtIxKFiJKQrBoMGTbUEqcQa5kd0T6BEHjpAchU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
